a=float(input('A digite um número: '))
b=float(input('digite outro: '))
s=(a+b)
su=(a-b)
us=(b-a)
m=(a*b)
d=(a/b)
dd=(b/a)
pot=(a**b)
top=(b**a)
di=(a//b)
id=(b//a)
po=(a%b)
op=(b%a)
print('A soma entre eles é: {}'.format(s))
print('A subtração entre eles é: {} ou {}'.format(su,us))
print('A multipicação entre eles é: {}'.format(m))
print('A divisão entre eles é: {:.4f} ou {:.4f'
      '}'.format(a/b,b/a))
print('A divisão inteira entre eles é: {:.4f} ou {:.4f}'.format(di,id))
print('A potenciação entre eles é: {} ou {}'.format(pot,top))
print('A porcentagem entre eles é: {:.4f} ou {:.4f}'.format(po,op))
